services: 
  orchestrator: 
    build: ./orchestrator
    ports:
      - "5000:80"
    environment:
      PASS_REDIS: ${PASS_REDIS}
      APP_URL: ${APP_URL} 
      USER_URL: ${USER_URL}
  app: 
    build: ./services/app
    ports:
      - "5002:4002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  user: 
    build: ./services/users
    ports:
      - "5001:4001"
    environment:
      MONGODB_URL: ${MONGODB_URL}
  